export const apps = [
  {
    id: 'ingrelab',
    appId: 1,
    title: 'IngreLab',
    tagline: 'Food Intelligence.',
    description: `These days we rarely know what is in our food. High sugar, high inflammatory, ultra-processed food has taken up a huge portion of our daily food intake.<br><br>

IngreLab peels away the fancy packaging and drills down to the ingredients. You just scan the barcode, and it analyzes these health risk factors and builds a risk profile on the ingredients.<br><br>

We all should know what we eat. IngreLab powers your “Food Intelligence”.`,
    images: [
      'ingrelab_login.jpeg',
      'ingrelab_home.jpeg',
      'ingrelab_categories.jpeg',
      'ingrelab_product.jpeg',
      'ingrelab_ingredients.jpeg',
    ],
    videos: [
      {
        id: 'app-youtube-player-1',
        videoId: 'lyOfGwCf9XA',
        title: 'IngreLab',
      },
    ],
    link: 'https://ingrelab.scottsun.io',
    showLink: true,
  },
  {
    id: 'tuneitall',
    appId: 2,
    title: 'Tune It All',
    tagline: 'The only guitar pal you need.',
    description: `Tune It All is an IOS tuner app but with something extra.<br><br>
    
    In here, you can tune any guitar, bass, ukulele in any tuning you can think of. You can also compose your own string orchestra backing track with any chord you want. Beautiful playing with beautiful tracks.<br><br>
    
    I built this app because I love guitar, but the tuner apps out there usually have inconsistent quality, and special tunings are often gated. I want an all-in-one tuner app that does everything I need, so I built it myself.<br><br>
    
    Happy practicing!`,
    images: [
      'tuneitall1.jpeg',
      'tuneitall2.jpeg',
      'tuneitall3.jpeg',
      'tuneitall4.jpeg',
    ],
    link: 'https://tuneitall.scottsun.io',
    showLink: true,
  },
  {
    id: 'mycraft',
    appId: 3,
    title: 'MyCraft',
    tagline: `It's cozy in the browser.`,
    description: `MyCraft is a MineCraft-like mini game that runs in your browser. I made it with React and Three.js.<br><br>
    
    Enjoy the sunny beams, cozy view, and smooth music. And you might even build something here and share it with your friends.`,
    images: [
      'mycraft_start.jpeg',
      'mycraft_world.jpeg',
      'mycraft_sunset.jpeg',
      'mycraft_underwater.jpeg',
    ],
    videos: [
      {
        id: 'app-youtube-player-2',
        videoId: 'Jxn7g5fzAto',
        title: 'MyCraft',
      },
    ],
    link: 'https://mycraft.scottsun.io',
    showLink: true,
  },
  {
    id: 'learntube',
    appId: 4,
    title: 'LearnTube',
    tagline: 'Video to insights in seconds.',
    description: `Too many long-form podcasts and interviews and no time to watch? Just copy the video link, and LearnTube lays insights bare in seconds.<br><br>

• A report on the video exploring content<br><br>
• Ask any questions about the video<br><br>
• Select any part of the report for deeper elaboration<br><br>
• Generate Mind Map on the fly for conceptual and structural understanding<br><br>
• Share the report with anyone with a URL or save it as a PDF<br><br>

TL;DW (Too Long; Don't Watch) summaries or in-depth explorations, all in seconds.`,
    images: [
      'learntube1.jpeg',
      'learntube2.jpeg',
      'learntube3.jpeg',
      'learntube4.jpeg',
      'learntube5.jpeg',
      'learntube6.jpeg',
    ],
    videos: [
      {
        id: 'app-youtube-player-3',
        videoId: 'vj1on8ByEmg',
        title: 'Use LearnTube | Video to insights to seconds',
      },
    ],
    link: 'https://learntube.scottsun.io',
    showLink: true,
  },
  {
    id: 'voxelit',
    appId: 5,
    title: 'Voxelit',
    tagline: 'Voxel scene to code.',
    description: `Voxelit is a Blender-like tiny voxel 3D editor.<br><br>
    
    You can build complex Minecraft-style scenes here, apply procedural and texture shaders, add and adjust lighting, and finally export your scene as is in HTML or TSX.<br><br>
    
    Have fun building it, and enjoy the convenience using it.`,
    images: ['voxelit1.jpeg', 'voxelit2.jpeg'],
    link: 'https://vx.scottsun.io',
    showLink: true,
  },
  {
    id: 'eventhorizon',
    appId: 6,
    title: 'Event Horizon',
    tagline: 'Awe in bending physics.',
    description: `Wandering on a lonesome and desolate planet orbiting a black hole. Face the event horizon.`,
    images: ['eventhorizon1.jpeg', 'eventhorizon2.jpeg'],
    link: 'https://eventhorizon.scottsun.io',
    showLink: true,
  },
  {
    id: 'imgsherlock',
    appId: 7,
    title: 'ImgSherlock',
    tagline: 'MLLM vs. MLLM.',
    description: `After I saw a post about how real-looking an image of a receipt generated by GPT-4o native image gen was, and how all traditional ML AI-image detection had failed at that image, I thought there is a more capable way to do AI image detection.<br><br>

You see, SoTA AI image generation has become so advanced that depending solely on visual analysis is not adequate enough anymore, one must also analyze the plausibility of the image, including the internal consistency of the information, elements, and subjects in the image. This can be done with Multimodal reasoning LLMs.<br><br>

ImgSherlock is a web app that allows you to upload an image, identify if it's likely AI-generated, and get a detailed analysis.<br><br>`,
    images: ['imgsherlock1.jpeg', 'imgsherlock2.jpeg'],
    link: 'https://imgsherlock.scottsun.io',
    showLink: true,
  },
  {
    id: 'jobguru',
    appId: 8,
    title: 'Job Guru',
    status: {
      type: 'no-longer-deployed',
      label: 'No Longer Deployed',
    },
    tagline: 'Ingenious job landing craft.',
    description: `Job Guru is your go-to tool for creating outstanding CVs, resumes, and cover letters that make an impact. Simply input details like company information, job descriptions, specific requests, and your personal profile, and the app will customize each document to suit your needs and the role you're aiming for.<br><br>

What makes Job Guru truly unique is its innovative keyword match analysis. This feature meticulously compares your written document to the original job description, breaking it down sentence by sentence. It provides clear insights to ensure your application emphasizes the skills, experiences, and terms that employers care about most.<br><br>

With Job Guru, you're not just writing—you're crafting a tailored, strategic application that boosts your chances of landing the job.<br><br>`,
    images: ['jobguru1.jpeg', 'jobguru2.jpeg', 'jobguru3.jpeg'],
    link: 'https://github.com/scottstts/jobguru-production',
    showLink: false,
  },
];
