export const apps = [
  {
    id: 'learntube',
    projectId: 8,
    title: 'LearnTube',
    tagline: 'Video to insights in seconds.',
    description: `Unlock the full potential of YouTube videos with LearnTube. Provide a YouTube video link, and LearnTube delivers a tailored report on the video's content, customized to your preferred length and depth. Whether you want a concise overview or a detailed breakdown, LearnTube adapts to your needs.<br><br>

Interact seamlessly with AI: chat to ask questions about the video or select any sentence from the report for deeper elaboration. Generate Mind Map on the fly for conceptual and structural understanding. Save and share the insights by exporting reports to PDF, and keep your projects organized in the Collection tab for easy access anytime.<br><br>

Tailored for YouTube—especially long-form interviews and podcasts—LearnTube is your dedicated companion, saving time with quick TL;DW (Too Long; Didn't Watch) summaries or offering in-depth explorations, all at your fingertips.`,
    images: [
      'learntube1.jpeg',
      'learntube2.jpeg',
      'learntube3.jpeg',
      'learntube4.jpeg',
      'learntube5.jpeg',
      'learntube6.jpeg',
    ],
    link: 'https://learntube.scottsun.io',
  },
  {
    id: 'jobguru',
    projectId: 9,
    title: 'Job Guru',
    tagline: 'Ingenious job landing craft.',
    description: `Job Guru is your go-to tool for creating outstanding CVs, resumes, and cover letters that make an impact. Simply input details like company information, job descriptions, specific requests, and your personal profile, and the app will customize each document to suit your needs and the role you're aiming for.<br><br>

What makes Job Guru truly unique is its innovative keyword match analysis. This feature meticulously compares your written document to the original job description, breaking it down sentence by sentence. It provides clear insights to ensure your application emphasizes the skills, experiences, and terms that employers care about most.<br><br>

With Job Guru, you're not just writing—you're crafting a tailored, strategic application that boosts your chances of landing the job.`,
    images: ['jobguru1.jpeg', 'jobguru2.jpeg', 'jobguru3.jpeg'],
    link: 'https://jobguru.scottsun.io',
  },
  {
    id: 'imgsherlock',
    projectId: 10,
    title: 'ImgSherlock',
    tagline: 'MLLM vs. MLLM.',
    description: `After I saw a post about how real-looking an image of a receipt generated by GPT-4o native image gen was, and how all traditional ML AI-image detection had failed at that image, I thought there is a more capable way to do AI image detection.<br><br>

You see, SoTA AI image generation has become so advanced that depending solely on visual analysis is not adequate enough anymore, one must also analyze the plausibility of the image, including the internal consistency of the information, elements, and subjects in the image. This can be done with Multimodal reasoning LLMs.<br><br>

ImgSherlock is a web app that allows you to upload an image, identify if it's likely AI-generated, and get a detailed analysis.<br><br>`,
    images: ['imgsherlock1.jpeg', 'imgsherlock2.jpeg', 'imgsherlock3.jpeg'],
    link: 'https://imgsherlock.scottsun.io',
  },
];
